#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Apply migrations if has new one.
echo "Running migrations..."
python manage.py migrate

# --no-token means that the page won't ask for the generate token for access
# --headless because we are going to access the marimo from outside of the container
# &> /dev/null don't print the output on the console
echo "Starting marimo"
exec marimo edit --host 0.0.0.0 -p 2718 --no-token --headless &> /dev/null &

# -i the input.css for some tailwind directives or pure css,
# it will be added to the -o output.css in the
# tailwind processing, --watch=always is the hot reload.
echo "Starting tailwindcss watcher"
exec npx tailwindcss -i ./palindrome/static/css/input.css -o ./palindrome/static/css/output.css --watch=always &

echo "Starting runserver"
exec python manage.py runserver 0.0.0.0:8000